var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var html=document.querySelector("html"),loginPop=document.getElementById("login_pop"),openBtn=document.getElementById("user_acc"),closeBtn=document.getElementById("close_btn"),registerLink=document.querySelectorAll(".register_link"),seePassButt=document.querySelectorAll(".far.fa-eye-slash"),loginPass=document.getElementById("pass_inp"),signPassInp=document.getElementById("sign_pass_inp"),cartPop=document.getElementById("cart_pop"),cartCloseBtn=document.getElementById("cart_close_btn"),cartOpenBtn=
document.getElementById("user_orders"),loginForm=document.querySelectorAll(".login_form"),signinForm=document.querySelectorAll(".signin_form"),menuBtn=document.getElementById("menu_btn"),lsCloseBtn=document.getElementById("ls_close_btn"),lsMenu=document.getElementById("ls_menu"),lsMenuBck=document.getElementById("ls_menu_back"),lsMenuInfoBtn=document.querySelectorAll(".ls_info_btn"),lsMenuInfoHidden=document.getElementById("ls_info_hidden"),lsMenuInfoHidden2=document.getElementById("ls_info_hidden_2"),
lsLoginBtn=document.getElementById("ls_login_btn"),lsSigninBtn=document.getElementById("ls_signin_btn"),lsCartBtn=document.getElementById("cart_btn"),lsCatalogBtn=document.getElementById("ls_catalog_btn"),catalogBtn=document.getElementById("catalog_btn"),catalogPop=document.getElementById("catalog_pop"),searchResults=document.getElementById("search_results"),searchField=document.getElementById("search_field"),searchResList=document.getElementById("search_results_list"),searchFormBck=document.getElementById("search_form_back"),
searchClearBtn=document.getElementById("search_clear_btn"),catalogCtgries=document.getElementById("catalog_categories").children,catalogPrdcts=document.getElementById("catalog_products").children,catalogCloseBtn=document.querySelectorAll(".catalog_close_btn"),catalogHead=document.getElementById("catalog_head"),catalogToAll=document.getElementById("to_all_categories"),expandBtns=document.querySelectorAll(".expand_btn"),offerSections=document.querySelectorAll(".main_offers_list"),loadingElem=document.querySelector(".end_content_loading_elem"),
asideLoginBtn=document.getElementById("aside_register_btn"),mobileCatalogBtn=document.getElementById("mobile_catalog_btn"),mainLikeBtns=document.querySelectorAll(".main_offers_like_btn"),tabletCatalog=document.querySelectorAll(".main_catalog_tablet_category"),mainOffers=document.querySelector(".main_offers"),swiper=new Swiper(".swiper",{direction:"horizontal",loop:!0,speed:600,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},autoplay:{delay:5E3,disableOnInteraction:!1}}),screenSize=
window.innerWidth,prevElem=0,windowTimeout,flag=!0;
function screenSizeAffect(){if(1023>=screenSize){for(var a=$jscomp.makeIterator(catalogCtgries),b=a.next();!b.done;b=a.next())category=b.value,category.addEventListener("click",catalogAction),category.removeEventListener("mouseenter",catalogAction);flag&&(catalogCtgries[prevElem].style.backgroundColor="#fff",catalogCtgries[prevElem].child.style.display="none",flag=!1)}else if(1023<screenSize){a=$jscomp.makeIterator(catalogCtgries);for(b=a.next();!b.done;b=a.next())category=b.value,category.removeEventListener("click",
catalogAction),category.addEventListener("mouseenter",catalogAction);catalogCtgries[prevElem].style.backgroundColor="#f3f3f3";catalogCtgries[prevElem].child.style.display="flex";flag=!0;catalogToAll.style.display="none";catalogCtgries[0].parentNode.style.display="block"}}window.addEventListener("resize",function(){screenSize=window.innerWidth;screenSizeAffect()});
for(var i=0;i<catalogPrdcts.length-1;i++)tabletCatalog[i].child=catalogPrdcts.item(i+1),tabletCatalog[i].id=i+1,catalogCtgries[i].child=catalogPrdcts.item(i+1),catalogCtgries[i].id=i+1,tabletCatalog[i].addEventListener("click",tabletCatalogAction);
function catalogAction(){1023>=screenSize?(catalogToAll.style.display="flex",catalogCtgries[0].parentNode.style.display="none",this.child.style.display="flex",catalogHead.innerHTML=this.innerText,prevElem=this.id-1):1023<screenSize&&(catalogCtgries[prevElem].style.backgroundColor="#fff",catalogCtgries[prevElem].child.style.display="none",this.style.backgroundColor="#f3f3f3",this.child.style.display="flex",prevElem=this.id-1)}
function openPop(){html.classList.add("lock_scroll");if(this===openBtn||this===lsLoginBtn)loginPop.classList.remove("close"),loginForm.forEach(function(a){return a.classList.add("visible")}),signinForm.forEach(function(a){return a.classList.remove("visible")}),catalogBtn.children[0].classList.remove("fa-times"),catalogPop.classList.add("close");else if(this===cartOpenBtn||this===lsCartBtn)catalogBtn.children[0].classList.remove("fa-times"),catalogPop.classList.add("close"),cartPop.classList.remove("close");
else if(this===lsSigninBtn)loginPop.classList.remove("close"),loginForm.forEach(function(a){return a.classList.remove("visible")}),signinForm.forEach(function(a){return a.classList.add("visible")}),catalogBtn.children[0].classList.remove("fa-times"),catalogPop.classList.add("close");else if(this===catalogBtn||this===lsCatalogBtn)screenSizeAffect(),catalogBtn.children[0].classList.add("fa-times"),catalogPop.classList.remove("close");search("");seePassButt.forEach(function(a){return a.classList.add("fa-eye-slash")})}
function closePop(a){if(a)a.target===loginPop||a.currentTarget===closeBtn?(html.classList.remove("lock_scroll"),loginPop.classList.add("close")):a.target===cartPop||a.currentTarget===cartCloseBtn?(html.classList.remove("lock_scroll"),cartPop.classList.add("close")):a.target===catalogPop&&(html.classList.remove("lock_scroll"),catalogCtgries[0].parentNode.style.display="block",catalogBtn.children[0].classList.remove("fa-times"),catalogPop.classList.add("close"));else if(this===catalogBtn||this===searchField)html.classList.remove("lock_scroll"),
catalogCtgries[0].parentNode.style.display="block",catalogBtn.children[0].classList.remove("fa-times"),catalogPop.classList.add("close")}function actionInLogInPop(){loginPass.setAttribute("type","password");signPassInp.setAttribute("type","password");seePassButt.forEach(function(a){return a.classList.add("fa-eye-slash")});signinForm.forEach(function(a){return a.classList.toggle("visible")});loginForm.forEach(function(a){return a.classList.toggle("visible")})}
function seePass(){var a=loginPass.getAttribute("type"),b=signPassInp.getAttribute("type");"password"===a?loginPass.setAttribute("type","text"):loginPass.setAttribute("type","password");"password"===b?signPassInp.setAttribute("type","text"):signPassInp.setAttribute("type","password");this.classList.toggle("fa-eye-slash")}
function actionLeftSide(){search("");this===menuBtn?(html.classList.add("lock_scroll"),lsMenu.classList.add("open_menu"),lsMenuBck.classList.remove("close"),catalogBtn.children[0].classList.remove("fa-times"),catalogPop.classList.add("close")):(html.classList.remove("lock_scroll"),lsMenu.classList.remove("open_menu"),lsMenuBck.classList.add("close"))}
function actionLsInfo(){"1"===this.parentNode.id?lsMenuInfoHidden.classList.toggle("open_lsinfo_hidden"):lsMenuInfoHidden2.classList.toggle("open_lsinfo_hidden")}function lsOpenLink(){actionLeftSide.call(this);openPop.call(this)}function actionCatalog(){catalogBtn.children[0].classList.toggle("fa-times");catalogPop.classList.contains("close")?openPop.call(this):closePop.call(this)}var inpTimeOut;
searchField.addEventListener("input",function(){searchField.value?(clearTimeout(inpTimeOut),inpTimeOut=setTimeout(function(){return search(searchField.value)},400)):(searchClearBtn.style.display="none",search(searchField.value))});searchField.addEventListener("focus",function(){closePop.call(searchField);search(searchField.value)});
function search(a){searchResList.innerHTML="";if(a){searchClearBtn.style.borderRadius="0px 4px 0px 0px";searchClearBtn.style.display="block";searchResults.parentNode.parentNode.style.borderBottomLeftRadius="0px";searchResults.classList.remove("close");searchFormBck.classList.remove("close");var b=mockDB.filter(function(c){return c.toUpperCase().startsWith(a.toUpperCase())});0!=b.length?(b.length=10,b.forEach(function(c){c='<a href=""><span>'+a.toLowerCase()+"</span>"+c.slice(a.length).toLowerCase()+
"</a>\n";var d=document.createElement("li");d.innerHTML=c;searchResList.appendChild(d)})):0===b.length&&(b=document.createElement("li"),b.innerHTML=' <a href=""> Nothing found for your request </a>\n',b.children[0].style.color="#000",searchResList.appendChild(b))}else searchClearBtn.style.borderRadius="4px",searchResults.parentNode.parentNode.style.borderBottomLeftRadius="4px",searchFormBck.classList.add("close"),searchResults.classList.add("close")}
for(var i$2=0;i$2<offerSections.length;i$2++)expandBtns[i$2].parent=offerSections[i$2];function expandOffer(a){a.currentTarget.classList.add("closed");a.currentTarget.parent.classList.add("expanded")}var windowPos,windowEnd,pageTimeout,closedSections=document.querySelectorAll(".main_offers_container.closed"),counter=0;window.addEventListener("scroll",expandPage);
function expandPage(){windowEnd=document.body.offsetHeight-2*loadingElem.clientHeight;windowPos=window.innerHeight+window.scrollY;windowPos>=windowEnd&&counter!==closedSections.length?(clearTimeout(pageTimeout),pageTimeout=setTimeout(function(){closedSections[counter].classList.remove("closed");counter+=1},400)):counter===closedSections.length&&(loadingElem.parentNode.style.display="none")}function liked(){this.children[0].classList.toggle("fas")}
function tabletCatalogAction(){openPop.call(catalogBtn);catalogAction.call(this)}registerLink.forEach(function(a){return a.addEventListener("click",actionInLogInPop)});seePassButt.forEach(function(a){return a.addEventListener("click",seePass)});openBtn.addEventListener("click",openPop);loginPop.addEventListener("click",closePop);closeBtn.addEventListener("click",closePop);asideLoginBtn.addEventListener("click",function(){return openPop.call(openBtn)});mobileCatalogBtn.addEventListener("click",function(){return openPop.call(catalogBtn)});
mainLikeBtns.forEach(function(a){return a.addEventListener("click",liked)});cartOpenBtn.addEventListener("click",openPop);cartPop.addEventListener("click",closePop);cartCloseBtn.addEventListener("click",closePop);lsCloseBtn.addEventListener("click",actionLeftSide);lsMenuBck.addEventListener("click",actionLeftSide);menuBtn.addEventListener("click",actionLeftSide);lsMenuInfoBtn.forEach(function(a){return a.addEventListener("click",actionLsInfo)});lsLoginBtn.addEventListener("click",lsOpenLink);
lsSigninBtn.addEventListener("click",lsOpenLink);lsCartBtn.addEventListener("click",lsOpenLink);lsCatalogBtn.addEventListener("click",lsOpenLink);catalogBtn.addEventListener("click",actionCatalog);catalogPop.addEventListener("click",closePop);
catalogCloseBtn.forEach(function(a){return a.addEventListener("click",function(){html.classList.remove("lock_scroll");catalogToAll.style.display="none";catalogHead.innerText="Catalog";catalogBtn.children[0].classList.remove("fa-times");catalogCtgries[0].parentNode.style.display="block";catalogPop.classList.add("close");flag=!0;screenSizeAffect()})});
catalogToAll.addEventListener("click",function(){catalogToAll.style.display="none";catalogCtgries[0].parentNode.style.display="block";catalogCtgries[prevElem].child.style.display="none";catalogHead.innerHTML="Catalog"});searchFormBck.addEventListener("click",function(){return search("")});searchClearBtn.addEventListener("click",function(){search("");searchField.value="";searchClearBtn.style.display="none"});expandBtns.forEach(function(a){return a.addEventListener("click",expandOffer)});
var mockDB="Laptops;Asus;Acer;HP(Hewlett Packard);Dell;Apple;Fleshdisk USB;Laptop bags;Laptop stands;Powerbanks;Cables and adapters;Tablets;Accessories for tablets;Cases and keyboards for tablets;Protective glasses;Graphics tablets;eBooks;Accessories for eBooks;Videocards;Hard drives;Processors;SSD;Memory;Motherboards;Power supplies;Computer cases;Cooler systems;Sound cards;Computers;Monitors;Mouses;Keyboards".split(";");